Agenda
marik22312/radiosavta-next pull request #39
Opened 2021-12-25 20:08 UTC by asaf147369

2021-12-30 09:34 UTC, marik22312 requested changes

2021-12-30 09:34 UTC, marik22312 commented on hook/useAgenda.ts
> +// import { getCurrentSongTitle } from "../api/RadioInfo.api";
please remove unneeded comments

2021-12-30 09:34 UTC, marik22312 commented on hook/useAgenda.ts
> +    data
consider returning the data as `agenda` property, instead of `data`, to keep things more understandable

2021-12-30 09:34 UTC, marik22312 commented on components/Agenda/Agenda.tsx
> +    const schedule = useAgenda();
consider renaming to `agenda` for consistency, or even better, destructure this and use just the properties you need

2021-12-30 09:35 UTC, marik22312 commented on components/Agenda/Agenda.tsx
> +    const schedule = useAgenda();
as in 
```tsx
const {agenda} = useAgenda();
```

2022-01-03 20:08 UTC, asaf147369 commented on components/Agenda/Agenda.tsx
> +    const schedule = useAgenda();
Not really sure how to destructure further then const { data } = useAgenda() and then data?.schedule

2022-01-16 20:17 UTC, merged