Landing page2
marik22312/radiosavta-next pull request #93
Opened 2023-02-18 21:07 UTC by asaf147369

2023-04-07 18:47 UTC, asaf147369 commented
LGTM 👍🏻

2023-04-07 20:33 UTC, marik22312 requested changes

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +    console.log("share failed")
please remove unnessecery log

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +    setImage(imageUrl || `${BASE_IMAGE_ICON}radiosavta/logo_head`)
not sure why we did that, but let's see if we can remove this effect as it has no real need

2023-04-07 20:33 UTC, marik22312 commented on domain/Player.ts
> +}
please prefer using string enums instead of the default numeric ones.
might cause bugs when checking their availability since in this case the `Initial` will default to `0`

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +    }
Please extract nested components to a standalone component.
declaring components as a function inside a functional component might cause issues with focus and renders

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +    }
https://levelup.gitconnected.com/code-review-avoid-declaring-react-component-inside-parent-component-1768a645f523

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +      {props.state === PlayerWrapperState.Inactive && inActiveContent()}
Consider wrapping this with a wrapper component, with an `if / return` logic inside

```
if (state1) return <Blah />
if (state2) return <SomeOther />
...
```

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +      {props.state === PlayerWrapperState.Inactive && inActiveContent()}
(Like you did in the broadcast icon)

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/PlayerWrapper/PlayerWrapper.tsx
> +      )}
not really sure what's going on here, perhaps it's possible to extract this to a function with a meaningful name to improve readability?

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/PlayerWrapper/PlayerWrapper.tsx
> +        )}
same as above

2023-04-07 20:33 UTC, marik22312 commented on components/FooterPlayer/PlayerWrapper/PlayerWrapper.tsx
> +        </button> */}
Please remove unused comment

2023-04-08 19:09 UTC, marik22312 requested changes

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +  const openClosePlayerButton = (mode: PlayerWrapperState) => (
please extract to be a component

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +  const inActiveContent = () => {
please extract to be a component

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +  const activeContent = () => {
please extract to be a component

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +  };
let's keep this consistent and use JSX markup instead of the mix of functions + jsx

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +      {renderContent()}
please use JSX to render components

2023-04-08 19:09 UTC, marik22312 commented on components/FooterPlayer/FooterPlayer.tsx
> +  return null;
this condition is redundant. if the code runs until this point it means that this condition is true

2023-04-08 20:52 UTC, merged